final value = {
  "Request": {
    "Consignee": {
      "AvailableDays": "",
      "AvailableTiming": "",
      "ConsigneeAddress1":
          "DNO:26-28-163/A|2/4 GANDHI NAGAR|AT AGRAHARAM|GUNTUR",
      "ConsigneeAddress2": " ",
      "ConsigneeAddress3": "",
      "ConsigneeAddressType": "",
      "ConsigneeAddressinfo": "",
      "ConsigneeAttention": "",
      "ConsigneeBusinessPartyTypeCode": "",
      "ConsigneeCityName": "",
      "ConsigneeCountryCode": "",
      "ConsigneeEmailID": "",
      "ConsigneeFiscalID": "",
      "ConsigneeFiscalIDType": "",
      "ConsigneeFullAddress": "",
      "ConsigneeGSTNumber": "",
      "ConsigneeID": "",
      "ConsigneeIDType": "",
      "ConsigneeLatitude": "",
      "ConsigneeLongitude": "",
      "ConsigneeMaskedContactNumber": "",
      "ConsigneeMobile": "9603866494",
      "ConsigneeName": "MR KALEKURI PAVAN KUMAR",
      "ConsigneePincode": "522004",
      "ConsigneeStateCode": "",
      "ConsigneeTelephone": "",
      "ConsingeeFederalTaxId": "",
      "ConsingeeRegistrationNumber": "",
      "ConsingeeRegistrationNumberIssuerCountryCode": "",
      "ConsingeeRegistrationNumberTypeCode": "",
      "ConsingeeStateTaxId": ""
    },
    "Returnadds": {
      "ManifestNumber": "",
      "ReturnAddress1": "YNT Supply Chain Pvt Ltd, 8 & 8A,",
      "ReturnAddress2": " ",
      "ReturnAddress3": "",
      "ReturnAddressinfo": "",
      "ReturnContact": "MR KALEKURI PAVAN KUMAR",
      "ReturnEmailID": "",
      "ReturnLatitude": "",
      "ReturnLongitude": "",
      "ReturnMaskedContactNumber": "",
      "ReturnMobile": "9987443311",
      "ReturnPincode": "522004",
      "ReturnTelephone": ""
    },
    "Services": {
      "AWBNo": "",
      "ActualWeight": "0.9",
      "AdditionalDeclaration": "",
      "AuthorizedDealerCode": "",
      "BankAccountNumber": "",
      "BillToAddressLine1": "",
      "BillToCity": "",
      "BillToCompanyName": "",
      "BillToContactName": "",
      "BillToCountryCode": "",
      "BillToCountryName": "",
      "BillToFederalTaxID": "",
      "BillToPhoneNumber": "",
      "BillToPostcode": "",
      "BillToState": "",
      "BillToSuburb": "",
      "BillingReference1": "",
      "BillingReference2": "",
      "CessCharge": 0.0,
      "CollectableAmount": 0.0,
      "Commodity": {
        "CommodityDetail1": "Manchester United Branded Football And Holdall",
        "CommodityDetail2": "Manchester United Branded Football And Holdall",
        "CommodityDetail3": "Manchester United Branded Football And Holdall"
      },
      "CreditReferenceNo": "1024531249",
      "CreditReferenceNo2": "",
      "CreditReferenceNo3": "",
      "CurrencyCode": "",
      "DeclaredValue": 1120.0,
      "DeliveryTimeSlot": "",
      "Dimensions": [
        {"Breadth": 0.4, "Count": 1, "Height": 0.16, "Length": 0.38}
      ],
      "ECCN": "",
      "EsellerPlatformName": "",
      "ExchangeWaybillNo": "",
      "ExportImportCode": "",
      "ExportReason": "",
      "ExporterAddressLine1": "",
      "ExporterAddressLine2": "",
      "ExporterAddressLine3": "",
      "ExporterBusinessPartyTypeCode": "",
      "ExporterCity": "",
      "ExporterCompanyName": "",
      "ExporterCountryCode": "",
      "ExporterCountryName": "",
      "ExporterDivision": "",
      "ExporterDivisionCode": "",
      "ExporterEmail": "",
      "ExporterFaxNumber": "",
      "ExporterMobilePhoneNumber": "",
      "ExporterPersonName": "",
      "ExporterPhoneNumber": "",
      "ExporterPostalCode": "",
      "ExporterRegistrationNumber": "",
      "ExporterRegistrationNumberIssuerCountryCode": "",
      "ExporterRegistrationNumberTypeCode": "",
      "ExporterSuiteDepartmentName": "",
      "FavouringName": "",
      "ForwardAWBNo": "",
      "ForwardLogisticCompName": "",
      "FreightCharge": 0.0,
      "GovNongovType": "",
      "IncotermCode": "",
      "InsuranceAmount": 0.0,
      "InsurancePaidBy": "",
      "InsurenceCharge": 0.0,
      "InvoiceNo": "",
      "IsCargoShipment": false,
      "IsChequeDD": "",
      "IsCommercialShipment": false,
      "IsDedicatedDeliveryNetwork": false,
      "IsDutyTaxPaidByShipper": false,
      "IsEcomUser": false,
      "IsForcePickup": false,
      "IsIntlEcomCSBUser": false,
      "IsPartialPickup": false,
      "IsReversePickup": false,
      "ItemCount": "1",
      "MarketplaceName": "",
      "MarketplaceURL": "",
      "NFEIFlag": false,
      "NotificationMessage": "",
      "Officecutofftime": "",
      "OrderURL": "",
      "PDFOutputNotRequired": false,
      "PackType": "",
      "ParcelShopCode": "",
      "PayableAt": "",
      "PayerGSTVAT": 0.0,
      "PickupDate": "/Date(1716353473000)/",
      "PickupMode": "",
      "PickupTime": "1021",
      "PickupType": "",
      "PieceCount": "1",
      "PreferredPickupTimeSlot": "",
      "ProductCode": "D",
      "ProductFeature": "",
      "ProductType": 1,
      "RegisterPickup": true,
      "ReverseCharge": 0.0,
      "SignatureName": "",
      "SignatureTitle": "",
      "SpecialInstruction": "",
      "SubProductCode": "",
      "SupplyOfIGST": "",
      "SupplyOfwoIGST": "",
      "TermsOfTrade": "",
      "TotalCashPaytoCustomer": 0.0,
      "Total_IGST_Paid": 0.0,
      "itemImg": "",
      "itemdtl": [
        {
          "CGSTAmount": 0.0,
          "CommodityCode": "",
          "Discount": 0.0,
          "HSCode": "",
          "IGSTAmount": 0.0,
          "IGSTRate": 0.0,
          "Instruction": "",
          "InvoiceNumber": "",
          "IsMEISS": "",
          "ItemID": "419FU",
          "ItemName": "Manchester United Branded Football And Holdall",
          "ItemValue": 0,
          "Itemquantity": "1",
          "LicenseNumber": "",
          "ManufactureCountryCode": "",
          "ManufactureCountryName": "",
          "PerUnitRate": 0.0,
          "PieceID": "",
          "PieceIGSTPercentage": 0.0,
          "PlaceofSupply": "",
          "ProductDesc1": "",
          "ProductDesc2": "",
          "ReturnReason": "",
          "SGSTAmount": 0.0,
          "SKUNumber": "",
          "SellerGSTNNumber": "",
          "SellerName": "",
          "SubProduct1": "",
          "SubProduct2": "",
          "SubProduct3": "",
          "SubProduct4": "",
          "TaxableAmount": 0.0,
          "TotalValue": "1120",
          "Unit": "",
          "Weight": 0.0,
          "cessAmount": "0.0",
          "countryOfOrigin": "",
          "docType": "",
          "subSupplyType": 0,
          "supplyType": ""
        }
      ],
      "noOfDCGiven": 0
    },
    "Shipper": {
      "CustomerAddress1": "8 & 8A,",
      "CustomerAddress2": "DRR Avenue, Audco Nagar,Kattupakkam",
      "CustomerAddress3": "Chennai 600056",
      "CustomerAddressinfo": "",
      "CustomerBusinessPartyTypeCode": "",
      "CustomerCode": "268030",
      "CustomerEmailID": "",
      "CustomerFiscalID": "",
      "CustomerFiscalIDType": "",
      "CustomerGSTNumber": "",
      "CustomerLatitude": "",
      "CustomerLongitude": "",
      "CustomerMaskedContactNumber": "",
      "CustomerMobile": "9987443311",
      "CustomerName": "YNT Supply Chain Pvt Ltd",
      "CustomerPincode": "600056",
      "CustomerRegistrationNumber": "",
      "CustomerRegistrationNumberIssuerCountryCode": "",
      "CustomerRegistrationNumberTypeCode": "",
      "CustomerTelephone": "",
      "IsToPayCustomer": false,
      "OriginArea": "MAA",
      "Sender": "",
      "VendorCode": ""
    }
  },
  "Profile": {
    "Api_type": "S",
    "Area": "MAA",
    "Customercode": "268030",
    "IsAdmin": "",
    "LicenceKey": "kprno0tuqfqkvq0eklhuf4amtlafjkmi",
    "LoginID": "MAA60185",
    "Version": "1.8"
  }
};
